---
title: "HitBTC"
author: "Zhuojue Wang"
date: '2022-06-03'
output: html_document
---
```{r}
library(pins)
library(tidyverse)
library(httr)
library(jsonlite)
library(cryptowatchR)
```

```{r}
# Settings
exchange <- "kraken"
pair <- "btcusd"
route <- "ohlc"
api_key ='6NO31ET00O220TWYIMDR'

# Daily prices for longest possible time period
markets.btcusd <- get_markets(route, pair, exchange,api_key=api_key,allowance = TRUE)
markets.btcusd$result$`180` %>% as_tibble()
```
```{r}
get_pairs("btcusd")
```


```{r}
list_Supported_Currency <- c("AUD","CAD","CHF","EUR","GBP","JPY","USD")

x <- "USD"
x %in% list_Supported_Currency
```


```{r}
case <- fromJSON(content(GET("https://api.cryptowat.ch/pairs"), as = "text", encoding = "UTF-8"), flatten = TRUE)
case
```




```{r}
# all asset
case <- fromJSON(content(GET("https://api.cryptowat.ch/assets"), as = "text", encoding = "UTF-8"), flatten = TRUE)
case
```

```{r}
endpoint <- str_glue("https://api.cryptowat.ch/markets/kraken/{cryptocurrency}{currency}/ohlc",
                     cryptocurrency = "btc",
                     currency = "usd")
w <- GET(endpoint)
case <- fromJSON(content(w, as = "text", encoding = "UTF-8"), flatten = TRUE)
#7 day 
# CloseTime,
#   OpenPrice,
#   HighPrice,
#   LowPrice,
#   ClosePrice,
#   Volume,
#   QuoteVolume
```


```{r}
# select last 24 hr data with 3 mins inteval
closeprice_24 <- case$result$`180` %>% as_tibble() %>% tail(480) %>%
  rename(CloseTime=V1,OpenPrice=V2,HighPrice=V3,LowPrice=V4,ClosePrice=V5,Volume=V6,QuoteVolume=V7) 
closeprice_24
```
```{r}
library(lubridate)
closeprice_24$CloseTime <- closeprice_24$CloseTime %>% as_datetime() 
closeprice_24
```
```{r}
closeprice_24 %>% select(ClosePrice) %>% summary()
```



```{r}
#need to change the date in english form since my computer is in Chinese :(
Sys.setlocale("LC_TIME", "C")

ggplot(data = closeprice_24, 
       aes(x = CloseTime, y = ClosePrice)) + 
       xlab('Date Time (UTC)') +
       ylab('Price') +
       ggtitle(paste('Price Change Over Last 24 Hours -', "BTC"),
                          subtitle = paste('Most recent data collected on:', 'BTC','(UTC)')) +
       geom_line() + stat_smooth() + theme_economist()
```


